---

- name: check configuration  # noqa 301
  shell: >
    icinga2 daemon --validate --log-level debug --config /etc/icinga2/icinga2.conf
  register: icinga2_validate_config
  notify:
    - validated config

- name: validated config
  debug:
    var: icinga2_validate_config.stdout
  when: (
    icinga2_validate_config is defined and
    icinga2_validate_config.failed )

- name: restart icinga2  # noqa 301
  service:
    name: icinga2
    state: restarted

- name: restart icinga2 master
  remote_user: "{{ ansible_ssh_user }}"
  shell: >
    /etc/icinga2/restart_icinga2.sh '{{ ansible_fqdn }}'
  delegate_to: "{{ item.key }}"
  with_dict:
    "{{ icinga2_masters }}"

# - name: restart icinga2 master
#   uri:
#     url: "https://localhost:{{ icinga2_master_port | default(5665) }}/v1/actions/restart-process"
#     url_username: "{{ icinga2_api.user }}"
#     url_password: "{{ icinga2_api.password }}"
#     use_proxy: false
#     force_basic_auth: true
#     validate_certs: false
#     method: POST
#     http_agent: 'curl/7.69.1'
#     timeout: 10
#     headers:
#       Accept: "application/json"
#   delegate_to: "{{ item.key }}"
#   register: icinga2_downtime_system
#   with_dict:
#     "{{ icinga2_masters }}"

- name: icingadb-redis-restart
  service:
    name: "{{ icingadb_redis_service_name }}"
    state: restarted
    enabled: yes

- name: icingadb-restart
  service:
    name: "{{ icingadb_service_name }}"
    state: restarted
    enabled: yes
